const GUARDIAN_ACCESS_EVENT_TYPES = Object.freeze({
  FIRST_ACCESS_STARTED: 'FIRST_ACCESS_STARTED',
  FIRST_ACCESS_FAILED: 'FIRST_ACCESS_FAILED',
  RESPONSIBLE_VERIFIED: 'RESPONSIBLE_VERIFIED',
  RESPONSIBLE_VERIFICATION_FAILED: 'RESPONSIBLE_VERIFICATION_FAILED',
  PIN_SET: 'PIN_SET',
  PIN_SET_FAILED: 'PIN_SET_FAILED',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILED: 'LOGIN_FAILED',
  ACCOUNT_BLOCKED: 'ACCOUNT_BLOCKED',
  ACCOUNT_UNLOCKED: 'ACCOUNT_UNLOCKED',
  ACCOUNT_DEACTIVATED: 'ACCOUNT_DEACTIVATED',
  ACCOUNT_REACTIVATED: 'ACCOUNT_REACTIVATED',
  PIN_RESET: 'PIN_RESET',
  STUDENT_LINK_SYNCED: 'STUDENT_LINK_SYNCED',
  STUDENT_ALREADY_LINKED: 'STUDENT_ALREADY_LINKED',
  ACCOUNT_LINK_FAILED: 'ACCOUNT_LINK_FAILED',
  ACCOUNT_LINKED_WITH_EXISTING_PIN: 'ACCOUNT_LINKED_WITH_EXISTING_PIN',
  PIN_RECOVERY_STARTED: 'PIN_RECOVERY_STARTED',
  PIN_RECOVERY_FAILED: 'PIN_RECOVERY_FAILED',
  PIN_RECOVERY_BLOCKED: 'PIN_RECOVERY_BLOCKED',
  PIN_RECOVERY_SUCCEEDED: 'PIN_RECOVERY_SUCCEEDED',
});

const GUARDIAN_ACCESS_EVENT_TYPE_VALUES = Object.freeze(
  Object.values(GUARDIAN_ACCESS_EVENT_TYPES)
);

module.exports = {
  GUARDIAN_ACCESS_EVENT_TYPES,
  GUARDIAN_ACCESS_EVENT_TYPE_VALUES,
};
